### ISSUE TITLE
Possible to set cache dir?

### ISSUE THREAD

**Issue by onli** [voku/simple-cache#18]
Are feature requests okay here?

If I see that correctly the OpCache Constructor supports setting a cache dir, but the class above (Cache) seems to have no way to actually to set that variable when calling that constructor. Is there a way to configure it?

On some shared hosters you do not actually want to write to the configured PHP tmp directory, but rather to a project specific tmp directory.

**Comment by onli** [comment]
Yep, this really leads to problems in practice. I'll have a look at the code again to make sure I did not miss something and provide a PR if I did not.

**Comment by voku** [comment]
With version 4.0.0 you can overwrite the cache auto-detect via "CacheAdapterAutoManager" and the "$cacheAdapterManagerForAutoConnect" option in the "Cache"-constructor. Additional you can also activate the "$cacheAdapterManagerForAutoConnectOverwrite" option in the "Cache"-constructor, so that you can implement your own cache auto-detect logic.

```php
use voku\cache\Cache;

$cacheManager = new CacheAdapterAutoManager();

$cacheManager->addAdapter(
    AdapterOpCache::class,
    static function () {
        $cacheDir = \realpath(\sys_get_temp_dir()) . '/simple_php_cache_new';

        return $cacheDir;
    }
);

$cacheManager->addAdapter(
    AdapterArray::class
);
```

PS: some examples are in the tests ;) e.g. https://github.com/voku/simple-cache/blob/master/tests/CacheAutoInitReplaceTest.php#L132

**Comment by onli** [comment]
Thanks, this seems like the solution. I will test it out as soon as I have a moment.

**Comment by onli** [comment]
The test  code was useful to get the namespaces right, and it works fine. Thanks. https://github.com/s9y/Serendipity/commit/cd0adf55504e0b262b16fba6d83b4c743434a11d is how it looks like now.
